# Prometheus Configuration v2.45.0
# Main configuration file for VCMS monitoring with SLA and threshold monitoring

global:
  # Global settings for all scrape configurations
  scrape_interval: 30s     # Default scrape interval for metrics collection
  evaluation_interval: 30s # Interval for evaluating rules
  scrape_timeout: 10s     # Timeout for scrape requests
  
  # External labels added to any time series or alerts
  external_labels:
    environment: production
    cluster: vcms-cluster
    application: vessel-call-management

# Load alert rules from external file
rule_files:
  - "alert-rules.yml"

# Scrape configurations for monitoring targets
scrape_configs:
  # Kubernetes service endpoints monitoring configuration
  - job_name: kubernetes-service-endpoints
    honor_labels: true
    
    # Kubernetes service discovery configuration
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names: 
            - vcms
            - monitoring

    # Relabel configurations for service discovery
    relabel_configs:
      # Keep only services annotated for Prometheus scraping
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
        action: keep
        regex: true

      # Set metrics path based on annotation
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)

      # Add namespace label
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace

      # Add service name label
      - source_labels: [__meta_kubernetes_service_name]
        action: replace
        target_label: kubernetes_service_name

      # Add node name label
      - source_labels: [__meta_kubernetes_pod_node_name]
        action: replace
        target_label: kubernetes_node

    # Metric relabeling for specific system health indicators
    metric_relabel_configs:
      - source_labels: [__name__]
        action: keep
        regex: (container_memory_usage_bytes|container_cpu_usage_seconds_total|http_request_duration_seconds|http_requests_total)

# Alertmanager configuration
alerting:
  alertmanagers:
    - kubernetes_sd_configs:
        - role: pod
          namespaces:
            names: 
              - monitoring
          selectors:
            - role: alertmanager
              app: alertmanager
      
      path_prefix: /
      timeout: 10s
      api_version: v2
      scheme: http