# Loki Configuration v2.9.0
# Purpose: Enterprise-grade log aggregation and storage for Vessel Call Management System
# Retention: 7 days (168h) with secure deletion
# Rate Limits: 10MB/s with 20MB burst

auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: info
  http_server_read_timeout: 30s
  http_server_write_timeout: 30s
  grpc_server_max_recv_msg_size: 104857600  # 100MB
  grpc_server_max_send_msg_size: 104857600  # 100MB

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 1h
  max_chunk_age: 2h
  chunk_retain_period: 30s
  max_transfer_retries: 0
  wal:
    enabled: true
    dir: /loki/wal
  chunk_encoding: snappy

schema_config:
  configs:
    - from: "2023-01-01"
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    cache_ttl: 24h
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h  # 7 days
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  max_entries_limit_per_query: 10000
  max_global_streams_per_user: 5000
  max_query_length: 721h  # 30 days + 1 hour for queries
  max_query_parallelism: 32
  cardinality_limit: 100000
  max_streams_per_user: 10000
  max_line_size: 256000  # 256KB

chunk_store_config:
  max_look_back_period: 168h  # 7 days retention
  chunk_cache_config:
    enable_fifocache: true
    fifocache:
      max_size_bytes: 1073741824  # 1GB
      validity: 24h

table_manager:
  retention_deletes_enabled: true
  retention_period: 168h  # 7 days retention
  poll_interval: 15m

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules-temp
  alertmanager_url: http://alertmanager:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true
  enable_alertmanager_v2: true

analytics:
  reporting_enabled: false

tracing:
  enabled: true

query_scheduler:
  max_outstanding_requests_per_tenant: 100
  queue_length_cap: 50000

frontend:
  compress_responses: true
  log_queries_longer_than: 10s
  max_outstanding_per_tenant: 2000
  tail_proxy_url: http://localhost:3100

frontend_worker:
  frontend_address: localhost:9095
  grpc_client_config:
    max_send_msg_size: 104857600  # 100MB
    max_recv_msg_size: 104857600  # 100MB

querier:
  max_concurrent: 10
  query_timeout: 1m
  tail_max_duration: 1h
  extra_query_delay: 0s
  split_queries_by_interval: 30m
  align_queries_with_step: true
  max_query_parallelism: 32
  batch_iterators: true