apiVersion: v1
kind: Secret
metadata:
  name: vcms-secrets
  namespace: vcms
  labels:
    app: vcms
    component: secrets
    environment: production
  annotations:
    # Enable automated secret rotation
    rotation.kubernetes.io/trigger: "true"
    security.kubernetes.io/last-rotation: "2023-11-15T00:00:00Z"
    # Enable HashiCorp Vault integration
    vault.hashicorp.com/agent-inject: "true"
    # Add audit annotations
    audit.k8s.io/policy: "strict"
    security.kubernetes.io/encryption-provider: "aescbc"

type: Opaque
data:
  # Database credentials - Base64 encoded
  database_url: cG9zdGdyZXM6Ly9ob3N0PXZjbXMtZGItcHJvZC5wb3N0Z3Jlcy5kYXRhYmFzZS5henVyZS5jb206NTQzMi9kYj12Y21zP3NzbG1vZGU9cmVxdWlyZSZ0YXJnZXRfc2Vzc2lvbl9hdHRycz1yZWFkLXdyaXRl
  database_username: dmNtc19hcHBfdXNlcg==
  database_password: VkNNU19TdHJvbmdQYXNzd29yZCQyMDIz

  # JWT Configuration
  jwt_secret: VkNNU19KV1RfU2VjcmV0X0tleV8yMDIzXzUxMl9CaXRzX0xvbmdfU2VjdXJlX1N0cmluZ19Gb3JfU2lnbmluZ19Ub2tlbnM=
  jwt_expiration: MzYwMA==

  # OAuth2 Configuration for Azure AD
  oauth_client_id: dmNtc19vYXV0aF9jbGllbnRfaWQ=
  oauth_client_secret: dmNtc19vYXV0aF9jbGllbnRfc2VjcmV0

  # Infrastructure Services
  redis_password: VkNNU19SZWRpc19TdHJvbmdfUGFzc3dvcmQ=
  rabbitmq_password: VkNNU19SYWJiaXRNUV9TdHJvbmdfUGFzc3dvcmQ=

  # External Integration API Keys
  customs_api_key: VkNNU19DdXN0b21zX0FQSV9LZXk=
  immigration_api_key: VkNNU19JbW1pZ3JhdGlvbl9BUElfS2V5
  vts_api_key: VkNNU19WVFNfQVBJX0tleQ==
  weather_api_key: VkNNU19XZWF0aGVyX0FQSV9LZXk=

---
# Network Policy for Secret Access
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vcms-secrets-policy
  namespace: vcms
spec:
  podSelector:
    matchLabels:
      app: vcms
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: vcms
              component: backend
      ports:
        - protocol: TCP
          port: 8080

---
# Pod Security Policy
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: vcms-psp
  namespace: vcms
spec:
  privileged: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: MustRunAsNonRoot
  fsGroup:
    rule: RunAsAny
  volumes:
    - 'secret'
    - 'configMap'
    - 'emptyDir'